# Generated by Django 5.1 on 2024-09-08 02:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowrizonApp', '0004_academic_staff_content_managers_library_materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='academic_staff',
            name='academic_staff_idenity',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='academic_staff',
            name='academic_staff_phone',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='academic_staff',
            name='academic_staff_prefix',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='academic_staff',
            name='academic_staff_upload_approval',
            field=models.IntegerField(default=0),
        ),
    ]
