# Generated by Django 5.1 on 2024-10-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowrizonApp', '0007_content_managers_content_manager_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='academic_staff',
            name='academic_staff_gender',
            field=models.CharField(default='Not specified', max_length=50),
        ),
    ]
