# Generated by Django 5.1 on 2024-10-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowrizonApp', '0009_researchers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='student_fname',
            new_name='student_name',
        ),
        migrations.RemoveField(
            model_name='students',
            name='student_lname',
        ),
        migrations.AlterField(
            model_name='students',
            name='student_email',
            field=models.EmailField(default='Not specified', max_length=50),
        ),
    ]
