# Generated by Django 5.1 on 2024-10-19 12:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowrizonApp', '0011_rename_academmic_staff_idenity_academic_staff_academic_staff_identity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='admin',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admin',
            name='admin_created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='admin',
            name='admin_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='admin_password',
            field=models.CharField(default='default_password', max_length=128),
        ),
        migrations.AlterField(
            model_name='admin',
            name='admin_updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
