# Generated by Django 5.1 on 2024-10-25 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowrizonApp', '0013_alter_students_student_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
