# Generated by Django 4.0.6 on 2024-11-08 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowrizonApp', '0015_pdf_materials_remove_library_materials_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdf_materials',
            old_name='pdf_material_year',
            new_name='pdf_upload_date',
        ),
    ]
