# Generated by Django 4.0.6 on 2024-11-08 03:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('knowrizonApp', '0016_rename_pdf_material_year_pdf_materials_pdf_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf_materials',
            name='pdf_material_ref_id',
            field=models.CharField(default=datetime.datetime(2024, 11, 8, 3, 50, 47, 602880, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
    ]
