# Generated by Django 5.1 on 2024-09-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_fname', models.CharField(max_length=50)),
                ('admin_lname', models.CharField(max_length=50)),
                ('admin_email', models.EmailField(max_length=50)),
                ('admin_password', models.CharField(max_length=50)),
                ('admin_dept', models.CharField(max_length=50)),
                ('admin_created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
