# Generated by Django 5.1 on 2024-09-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowrizonApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_matric_no', models.CharField(max_length=50)),
                ('student_fname', models.CharField(max_length=50)),
                ('student_lname', models.CharField(max_length=50)),
                ('student_email', models.EmailField(max_length=50)),
                ('student_password', models.CharField(max_length=50)),
                ('students_gender', models.CharField(max_length=50)),
                ('student_dept', models.CharField(max_length=50)),
                ('student_created_at', models.DateTimeField(auto_now_add=True)),
                ('student_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
