# Generated by Django 5.1 on 2024-09-08 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowrizonApp', '0003_rename_students_gender_students_student_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='academic_staff',
            fields=[
                ('academic_staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('academic_staff_fname', models.CharField(max_length=50)),
                ('academic_staff_lname', models.CharField(max_length=50)),
                ('academic_staff_email', models.EmailField(max_length=50)),
                ('academic_staff_password', models.CharField(max_length=50)),
                ('academic_staff_upload_approval', models.IntegerField(default=0, max_length=50)),
                ('academic_staff_dept', models.CharField(max_length=50)),
                ('academic_staff_position', models.CharField(max_length=50)),
                ('research_interest', models.CharField(max_length=50)),
                ('academic_staff_created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_staff_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='content_managers',
            fields=[
                ('content_manager_id', models.AutoField(primary_key=True, serialize=False)),
                ('content_manager_fname', models.CharField(max_length=50)),
                ('content_manager_lname', models.CharField(max_length=50)),
                ('content_manager_email', models.EmailField(max_length=50)),
                ('contet_manager_phone', models.CharField(max_length=50)),
                ('content_manager_password', models.CharField(max_length=50)),
                ('content_manager_dept', models.CharField(max_length=50)),
                ('content_manager_created_at', models.DateTimeField(auto_now_add=True)),
                ('content_manager_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='library_materials',
            fields=[
                ('library_material_id', models.AutoField(primary_key=True, serialize=False)),
                ('library_material_title', models.CharField(max_length=50)),
                ('library_material_author', models.CharField(max_length=50)),
                ('library_material_publisher', models.CharField(max_length=50)),
                ('library_material_year', models.CharField(max_length=50)),
                ('library_material_type', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=50)),
                ('publication_date', models.DateField()),
                ('isbn', models.CharField(max_length=13)),
                ('format', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
                ('file', models.FileField(blank=True, null=True, upload_to='materials/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='materials/cover/')),
                ('availability_status', models.CharField(max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('tags', models.CharField(max_length=50)),
                ('library_material_created_at', models.DateTimeField(auto_now_add=True)),
                ('library_material_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
