# Generated by Django 5.1 on 2024-09-08 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowrizonApp', '0005_academic_staff_academic_staff_idenity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academic_staff',
            name='academic_staff_idenity',
        ),
        migrations.AddField(
            model_name='academic_staff',
            name='academic_staff_interest',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='academic_staff',
            name='academmic_staff_idenity',
            field=models.CharField(default='', max_length=50),
        ),
    ]
