# Generated by Django 5.1 on 2024-09-08 02:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowrizonApp', '0006_remove_academic_staff_academic_staff_idenity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content_managers',
            name='content_manager_prefix',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
