# Generated by Django 5.1 on 2024-10-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowrizonApp', '0008_academic_staff_academic_staff_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='researchers',
            fields=[
                ('researcher_id', models.AutoField(primary_key=True, serialize=False)),
                ('researcher_fname', models.CharField(max_length=50)),
                ('researcher_lname', models.CharField(max_length=50)),
                ('researcher_prefix', models.CharField(max_length=50)),
                ('researcher_email', models.EmailField(max_length=50)),
                ('researcher_password', models.CharField(max_length=50)),
                ('researcher_dept', models.CharField(max_length=50)),
                ('researcher_phone', models.CharField(max_length=50)),
                ('researcher_interest', models.CharField(max_length=50)),
                ('researcher_created_at', models.DateTimeField(auto_now_add=True)),
                ('researcher_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
