# Generated by Django 5.1 on 2024-10-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowrizonApp', '0010_rename_student_fname_students_student_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academic_staff',
            old_name='academmic_staff_idenity',
            new_name='academic_staff_identity',
        ),
        migrations.RemoveField(
            model_name='academic_staff',
            name='research_interest',
        ),
        migrations.AlterField(
            model_name='academic_staff',
            name='academic_staff_interest',
            field=models.CharField(default='interest', max_length=50),
        ),
    ]
