# Generated by Django 5.1 on 2024-10-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowrizonApp', '0012_admin_last_login_admin_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='student_password',
            field=models.CharField(max_length=200),
        ),
    ]
