# Generated by Django 5.1.5 on 2025-02-05 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowrizonApp', '0017_pdf_materials_pdf_material_ref_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal_materials',
            fields=[
                ('journal_material_id', models.AutoField(primary_key=True, serialize=False)),
                ('journal_material_title', models.CharField(max_length=50)),
                ('journal_material_author', models.CharField(max_length=50)),
                ('journal_material_category', models.CharField(max_length=50)),
                ('journal_upload_date', models.CharField(max_length=50)),
                ('journal_material_tags', models.CharField(max_length=50)),
                ('journal_for_department', models.CharField(max_length=50)),
                ('journal_for_faculty', models.CharField(max_length=50)),
                ('journal_for_level', models.CharField(max_length=50)),
                ('journal_material_description', models.CharField(max_length=255)),
                ('journal_material_file', models.FileField(blank=True, null=True, upload_to='materials/journals/')),
                ('journal_material_cover_image', models.ImageField(blank=True, null=True, upload_to='materials/journals/cover/')),
                ('journal_material_created_at', models.DateTimeField(auto_now_add=True)),
                ('journal_material_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
