# Generated by Django 5.1.5 on 2025-01-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowrizonApp', '0018_journal_materials_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academic_staff',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
