# Generated by Django 5.1.5 on 2025-01-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowrizonApp', '0020_alter_academic_staff_academic_staff_dept_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal_materials',
            old_name='journal_material_description',
            new_name='journal_material_abstract',
        ),
        migrations.RenameField(
            model_name='journal_materials',
            old_name='journal_upload_date',
            new_name='journal_pub_date',
        ),
        migrations.AddField(
            model_name='journal_materials',
            name='journal_material_type',
            field=models.CharField(default='not specified', max_length=200),
        ),
        migrations.AddField(
            model_name='journal_materials',
            name='journal_thematic_area1',
            field=models.CharField(default='not specified', max_length=250),
        ),
        migrations.AddField(
            model_name='journal_materials',
            name='journal_thematic_area2',
            field=models.CharField(default='not specified', max_length=250),
        ),
        migrations.AddField(
            model_name='journal_materials',
            name='journal_thematic_area3',
            field=models.CharField(default='not specified', max_length=250),
        ),
    ]
