# Generated by Django 5.1.5 on 2025-01-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowrizonApp', '0021_rename_journal_material_description_journal_materials_journal_material_abstract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal_materials',
            name='journal_material_ref_id',
            field=models.CharField(default='not specified', max_length=100),
        ),
        migrations.AlterField(
            model_name='journal_materials',
            name='journal_for_department',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='journal_materials',
            name='journal_for_faculty',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='journal_materials',
            name='journal_for_level',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='journal_materials',
            name='journal_material_author',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='journal_materials',
            name='journal_material_category',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='journal_materials',
            name='journal_material_tags',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='journal_materials',
            name='journal_material_title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='journal_materials',
            name='journal_pub_date',
            field=models.CharField(max_length=250),
        ),
    ]
