# Generated by Django 5.1.5 on 2025-01-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowrizonApp', '0022_journal_materials_journal_material_ref_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal_materials',
            name='journal_material_abstract',
            field=models.TextField(default='ABSTRACT NOT AVAILABLE', max_length=555),
        ),
    ]
