# Generated by Django 5.1.5 on 2025-01-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowrizonApp', '0023_alter_journal_materials_journal_material_abstract'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal_materials',
            name='staff_ID',
            field=models.CharField(default='not specified', max_length=250),
        ),
    ]
