# Generated by Django 5.1.5 on 2025-02-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowrizonApp', '0024_journal_materials_staff_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='open_access_databases',
            fields=[
                ('database_id', models.AutoField(primary_key=True, serialize=False)),
                ('database_title', models.CharField(max_length=250)),
                ('database_description', models.CharField(max_length=250)),
                ('database_genre', models.CharField(max_length=250)),
                ('database_cover_image', models.ImageField(blank=True, null=True, upload_to='materials/databases/cover/')),
                ('database_URL', models.CharField(max_length=250)),
                ('database_subscription', models.CharField(max_length=250)),
                ('database_created_at', models.DateTimeField(auto_now_add=True)),
                ('database_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
