# Generated by Django 5.1.5 on 2025-02-12 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowrizonApp', '0025_open_access_databases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='open_access_databases',
            name='database_description',
            field=models.CharField(max_length=800),
        ),
    ]
