# Generated by Django 5.1.5 on 2025-02-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowrizonApp', '0026_alter_open_access_databases_database_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='book_store',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_title', models.CharField(max_length=250)),
                ('book_author', models.CharField(max_length=250)),
                ('book_publisher', models.CharField(max_length=250)),
                ('book_year', models.CharField(max_length=250)),
                ('book_genre', models.CharField(max_length=250)),
                ('book_description', models.CharField(max_length=555)),
                ('book_ISBN', models.CharField(max_length=50)),
                ('book_cover_image', models.ImageField(blank=True, null=True, upload_to='materials/books/cover/')),
                ('book_created_at', models.DateTimeField(auto_now_add=True)),
                ('book_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
