# Generated by Django 5.1.5 on 2025-02-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowrizonApp', '0027_book_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_store',
            name='book_department',
            field=models.CharField(default='not specified', max_length=250),
        ),
        migrations.AddField(
            model_name='book_store',
            name='book_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='book_store',
            name='book_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
