# Generated by Django 5.1.5 on 2025-02-13 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowrizonApp', '0028_book_store_book_department_book_store_book_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='physical_library_materials',
            fields=[
                ('physical_library_material_id', models.AutoField(primary_key=True, serialize=False)),
                ('physical_library_material_title', models.CharField(max_length=250)),
                ('physical_library_material_author', models.CharField(max_length=250)),
                ('physical_library_material_publisher', models.CharField(max_length=250)),
                ('physical_library_material_year', models.CharField(max_length=250)),
                ('physical_library_material_type', models.CharField(max_length=250)),
                ('physical_library_material_description', models.CharField(max_length=555)),
                ('physical_library_material_genre', models.CharField(max_length=250)),
                ('physical_library_material_ISBN', models.CharField(max_length=50)),
                ('physical_library_material_format', models.CharField(max_length=50)),
                ('physical_library_material_cover_image', models.ImageField(blank=True, null=True, upload_to='materials/physical_library/cover/')),
                ('physical_library_material_created_at', models.DateTimeField(auto_now_add=True)),
                ('physical_library_material_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
