# Generated by Django 5.1.5 on 2025-02-13 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowrizonApp', '0029_physical_library_materials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physical_library_materials',
            name='physical_library_material_cover_image',
        ),
        migrations.AddField(
            model_name='physical_library_materials',
            name='physical_library_material_ref_id',
            field=models.CharField(default='not specified', max_length=250),
        ),
    ]
