# Generated by Django 5.1.5 on 2025-02-13 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowrizonApp', '0030_remove_physical_library_materials_physical_library_material_cover_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='physical_library_materials',
            old_name='physical_library_material_format',
            new_name='physical_library_material_department',
        ),
        migrations.AddField(
            model_name='physical_library_materials',
            name='physical_library_material_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
