# Generated by Django 5.1.5 on 2025-02-17 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowrizonApp', '0031_rename_physical_library_material_format_physical_library_materials_physical_library_material_departm'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff_public_profile',
            fields=[
                ('staff_profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_ID', models.CharField(default='not specified', max_length=250)),
                ('staff_fname', models.CharField(max_length=250)),
                ('staff_lname', models.CharField(max_length=250)),
                ('staff_interest', models.CharField(max_length=250)),
                ('staff_dept', models.CharField(max_length=250)),
                ('staff_email', models.EmailField(max_length=250)),
                ('staff_profile_picture', models.ImageField(blank=True, null=True, upload_to='staff/profile/')),
                ('staff_position', models.CharField(max_length=250)),
                ('staff_publication', models.CharField(max_length=250)),
                ('staff_bio', models.TextField(max_length=555)),
                ('staff_profile_created_at', models.DateTimeField(auto_now_add=True)),
                ('staff_profile_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
