# Generated by Django 5.1.5 on 2025-02-17 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowrizonApp', '0032_staff_public_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_public_profile',
            name='staff_profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='materials/staff/profile/'),
        ),
    ]
