# Generated by Django 5.1.5 on 2025-02-17 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowrizonApp', '0033_alter_staff_public_profile_staff_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_public_profile',
            name='staff_category',
            field=models.CharField(default='not specified', max_length=200),
        ),
    ]
