# Generated by Django 5.1.5 on 2025-02-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowrizonApp', '0034_staff_public_profile_staff_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_public_profile',
            name='staff_hindex',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
