# Generated by Django 5.1.5 on 2025-02-24 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowrizonApp', '0035_staff_public_profile_staff_hindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenAccessResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('source', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('indexed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
