# Generated by Django 5.1.5 on 2025-03-06 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowrizonApp', '0037_students_role_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='academic_staff',
            name='role',
            field=models.CharField(default='staff', max_length=20),
        ),
        migrations.AddField(
            model_name='content_managers',
            name='role',
            field=models.CharField(default='library_admin', max_length=20),
        ),
        migrations.AddField(
            model_name='researchers',
            name='role',
            field=models.CharField(default='researcher', max_length=20),
        ),
    ]
