# Generated by Django 5.1.5 on 2025-03-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowrizonApp', '0038_academic_staff_role_content_managers_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff_book_borrowers',
            fields=[
                ('staff_borrower_id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_ID', models.CharField(default='not specified', max_length=250)),
                ('staff_borrower_name', models.CharField(max_length=250)),
                ('staff_borrower_email', models.EmailField(max_length=250)),
                ('staff_borrower_dept', models.CharField(max_length=250)),
                ('staff_category', models.CharField(default='not specified', max_length=250)),
                ('book_title', models.CharField(max_length=250)),
                ('book_author', models.CharField(max_length=250)),
                ('book_number', models.CharField(max_length=250)),
                ('book_borrow_date', models.DateTimeField(auto_now_add=True)),
                ('book_return_date', models.DateTimeField(auto_now=True)),
                ('book_return_status', models.CharField(default='not returned', max_length=250)),
                ('staff_borrower_status', models.CharField(default='active', max_length=250)),
                ('staff_borrower_created_at', models.DateTimeField(auto_now_add=True)),
                ('staff_borrower_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
