# Generated by Django 5.1.5 on 2025-03-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowrizonApp', '0039_staff_book_borrowers'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_book_borrowers',
            fields=[
                ('student_borrower_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_ID', models.CharField(default='not specified', max_length=250)),
                ('student_borrower_name', models.CharField(max_length=250)),
                ('student_borrower_email', models.EmailField(max_length=250)),
                ('student_borrower_course', models.CharField(max_length=250)),
                ('student_borrower_dept', models.CharField(max_length=250)),
                ('book_title', models.CharField(max_length=250)),
                ('book_author', models.CharField(max_length=250)),
                ('book_number', models.CharField(max_length=250)),
                ('book_borrow_date', models.DateTimeField(auto_now_add=True)),
                ('book_return_date', models.DateTimeField(auto_now=True)),
                ('book_return_status', models.CharField(default='not returned', max_length=250)),
                ('student_borrower_status', models.CharField(default='active', max_length=250)),
                ('student_borrower_created_at', models.DateTimeField(auto_now_add=True)),
                ('student_borrower_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
