# Generated by Django 5.1.5 on 2025-03-09 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowrizonApp', '0040_student_book_borrowers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_book_borrowers',
            old_name='student_ID',
            new_name='student_mat_no',
        ),
        migrations.RemoveField(
            model_name='student_book_borrowers',
            name='student_borrower_course',
        ),
    ]
