# Generated by Django 5.1.5 on 2025-03-12 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowrizonApp', '0041_rename_student_id_student_book_borrowers_student_mat_no_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PDF_materials',
            new_name='library_digital_materials',
        ),
    ]
